### ISSUE TITLE
[VALIDATOR INTERRUPTION WITH ERROR DUPLICATE CHANNEL USE]

### ISSUE THREAD

**Issue by darshanjain12** [faucetsdn/udmi#1009]
Hi Team,

I’m encountering an issue where the validator halts intermittently, displaying the error below. I’d appreciate any suggestions for troubleshooting this.

Thank you!

<img width="593" alt="image" src="https://github.com/user-attachments/assets/8f1e2360-82bb-40a4-8f47-418bd01fb20a">

**Comment by grafnu** [comment]
What this usually means is that there's two instances of the tools running using the same channel.  Each channel supports one tool at a time. It is possible to have multiple channels if you need to run multiple tools.  If you include more of the log output then there might be details in there that indicate what the conflict would be with. Otherwise, we could try to look up the offending transaction ID and go from there.  If this is project-specific work then we might want to move this to a regular email thread (peringknife@google.com).
