### ISSUE TITLE
getting started help

### ISSUE THREAD

**Issue by bbartling** [faucetsdn/udmi#449]
Hi,

Apologize for submitting a git issue for this....but I am trying to soak in the learning cloud setup and site model for telemetry data:
https://github.com/faucetsdn/udmi/tree/master/docs/learning

And am just curious to ask at a high level (I work with BACnet systems & Python) can I build a Python based gateway device with the UDMI specification to get HVAC telemetry data to the Google IoT cloud platform? I am familiar with Python BACnet stacks and curious if I can work off of my existing knowledge for this...or is this project more node js based for IoT gateways?

Thank you.

**Comment by noursaidi** [comment]
Hi @bbartling 

Yes you can! UDMI is very much platform agnostic and compliments your use case very well. In fact I've also developed integrations into BMS systems including BACnet based on Python and I know of others who have also done similar 

For any questions, there is also the Google groups community https://groups.google.com/forum/#!forum/udmi-discuss which might be posting questions to, as it is received by the wider community. There is also a fortnightly working group which is joined by others like yourself which you might find useful.

**Comment by bbartling** [comment]
Great thank you. I joined the Google group in the link you posted but don't have enough permissions to start a "conversation." is it possible for myself to post in the "fortnightly working group" about any Python boiler plate code if it exists that I could build off of to make an IoT gateway?

**Comment by bbartling** [comment]
Is this write up outdated or anything I could start with? Seems Python base as well with a thermostat example:

https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/cloud-iot-gateways-rpi/index.md

**Comment by grafnu** [comment]
Ben, to use the udmi-discuss@ group I think you just send an email to udmi-discuss@groups.google.com -- I don't think there's any special permissions. I've never tried to start a conversation myself (did you mean through the website), rather just sent email. I have some answers to your questions, but I'd much rather handle them there on the list rather than through a github issue!

One thing to realize is there's a few different layers here -- there's the GCP IoT Core capability, which is the GoogleCloudPlatform you linked. Then there's the UDMI specification itself which is an interface layer (JSON encoding) that is nominally platform agnostic (i.e. will also work on AWS). Then there's a layer of auto-generated code for UDMI, which is mostly used in Java but should have some Python support (although might be buggy). There's also a concept of a "UDMI agent library" floating around, which hasn't quite been realized yet.

Hitting the email list would be best -- I'm 99% sure there's other people out there either working with Python gateways or would like to collaborate on something, so would at least be good to float the idea. The main bit of code I work with is Java based, so all the concepts are there but not in the form you're looking for!

**Comment by bbartling** [comment]
Thank you
